import os
import logging
from datetime import datetime
from models.state import RepoScribeState
from config.settings import get_settings

logger = logging.getLogger(__name__)


def format_output(state: RepoScribeState) -> RepoScribeState:
    """Assemble final blog Markdown and save to output directory."""
    if state.get("error"):
        return state

    logger.info("Formatting final blog output...")
    state["current_step"] = "formatting"

    outline = state.get("blog_outline", {})
    sections = state.get("blog_sections", {})
    title = outline.get("title", state.get("repo_name", "Untitled"))
    subtitle = outline.get("subtitle", "")
    tags = outline.get("tags", [])

    # Assemble blog content
    blog_parts = []

    # Write sections in order from outline
    for section in outline.get("sections", []):
        name = section.get("name", "")
        content = sections.get(name, "")
        if content:
            blog_parts.append(f"## {name}\n\n{content}")

    blog_body = "\n\n---\n\n".join(blog_parts)

    # Calculate metadata
    full_text = blog_body.replace("#", "").replace("*", "").replace("`", "")
    word_count = len(full_text.split())
    read_time = max(1, round(word_count / 200))

    # YAML frontmatter
    tags_str = ", ".join(f'"{t}"' for t in tags)
    frontmatter = f"""---
title: "{title}"
subtitle: "{subtitle}"
tags: [{tags_str}]
style: {state.get('blog_style', 'medium')}
tone: {state.get('blog_tone', 'technical')}
word_count: {word_count}
read_time: {read_time} min
repo: {state.get('github_url', '')}
generated_at: {datetime.utcnow().strftime('%Y-%m-%d')}
---"""

    # Add title and subtitle
    header = f"# {title}\n\n*{subtitle}*\n"

    final_blog = f"{frontmatter}\n\n{header}\n\n{blog_body}\n\n---\n\n*Generated by repo-scribe · [GitHub]({state.get('github_url', '')})*\n"

    state["final_blog"] = final_blog
    state["metadata"] = {
        "title": title,
        "subtitle": subtitle,
        "tags": tags,
        "word_count": word_count,
        "read_time": read_time,
        "style": state.get("blog_style", "medium"),
        "tone": state.get("blog_tone", "technical"),
        "repo": state.get("github_url", ""),
        "generated_at": datetime.utcnow().strftime("%Y-%m-%d"),
    }

    # Save to output directory
    settings = get_settings()
    os.makedirs(settings.OUTPUT_DIR, exist_ok=True)
    repo_name = state.get("repo_name", "blog").replace("/", "-").replace(" ", "-")
    output_path = os.path.join(settings.OUTPUT_DIR, f"{repo_name}_blog.md")

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(final_blog)

    logger.info(f"Blog saved to {output_path}")
    state["current_step"] = "done"
    return state
